dbpn/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'home/contact'

resources :listnames
resources :animals
resources :breeds

end

dbpn/app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :listname
  belongs_to :breed
end

dbpn/app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :animals
end

dbpn/app/models/listname.rb
class Listname < ActiveRecord::Base
  has_many :animals
end

dbpn/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

dbpn/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animals.all
  end

  def show_animals
    @animals = Animal.where(:listname_id) == params[:id])
  end

  def show_individual
    @animal = animals.find(params[:id])
  end
end

dbpn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dbpn/app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @breeds = Breed.all
  end

  def show_animals
    @animals = Animal.where(:breed_id) == params[:id]
  end
end

dbpn/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end
end

dbpn/app/controllers/listnames_controller.rb
class ListnamesController < ApplicationController
  
  def index 
    @listnames = Listname.all 
  end

  def new
    @listnames = Listname.new
  end

  def create
    @listname = Listname.new(listname_params)

    respond_to do |format|
      if @listname.save
        format.html { redirect_to @listname, notice: "New name was successfully added." }
      else
        format.html { render :new }
      end
    end
  end

  def show_animals
    @animals = Animal.where(:listname_id) == params[:id]
  end

end

dbpn/app/helpers/animals_helper.rb
module AnimalsHelper
end

dbpn/app/helpers/application_helper.rb
module ApplicationHelper
end

dbpn/app/helpers/breeds_helper.rb
module BreedsHelper
end

dbpn/app/helpers/home_helper.rb
module HomeHelper
end

dbpn/app/helpers/listnames_helper.rb
module ListnamesHelper
end

dbpn/app/views/animals/index.html.erb
<!-- This page could list all of the individual animals in the database with name and breed.
	EX: Aggie, bearded collie
			Brian, white banded snail
	Each entry should link to a SHOW page which lists the animals entire entry with name, breed, dates, and notes. (AJAX perhaps?) 
	Add and Edit Name links ? -->
	
<h1>Listing Animals</h1>

<table>
  <thead>
    <tr>
      <th>Animal</th>
      <th>Breed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |a| %>
      <tr>
        <td><%= a.aname %></td>
        <td><%= a.breed.breed %></td>
        <td><%= link_to 'Show', a %></td>
        <td><%= link_to 'Edit', edit_animal_path(a) %></td>
        <td><%= link_to 'Destroy', a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New Animal', new_animal_path %>

dbpn/app/views/animals/show.html.erb
<!--This page can display an individual animal entry with the name, breed, dates and
	notes of a specific animal_id.  It can be editable and have an option for Adding New Animal -->

dbpn/app/views/breeds/index.html.erb
<!--This page should list all of the breeds that are in the database.  
		EX: Airedale terrier
				Border collie
				Rabbit
		Each breed should appear only once even if multiple indvidual animals share that breed. Each breed should be linked to a page which lists all of the
		individual animals who share that breed. Add and Edit breed links? -->
		<h1>Master List of Breeds and Animal types</h1>
		<h3>Types of animals in our database.</h3>
		<p>Click on a breed/type to see the indvidual animals of that type.</p>
		<p><%= link_to 'Add a breed', new_breed_path %></p>
			<table>
				
			<tbody>
					<% @breeds.each do |breed| %>
					<tr><%= link_to breed.breed, breed_path(breed.breed) %></tr>
			</tbody>
		</table>

	</br>
<% end %>

dbpn/app/views/breeds/show.html.erb
<!--This page lists all of the individual animals who share a breed.
		EX: Airedale terrier, Archie
													Annie
		Each individual animal should be clickable and link to that
		individual's complete record with name, breed, dates, and notes.
		(AJAX ?) 
		Add and Edit Individual Animals links? -->

dbpn/app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display-->

		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" 
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" >Petnamesdb</a>
		</div>

		<!-- Collect the nav links, formas, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Names List', listnames_path %></li>
				<li><%= link_to 'Breeds/Animal types', breeds_path %></li>
				<li><%= link_to 'Contact', home_contact_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to 'Edit Profile', edit_user_session_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Login", new_user_session_path %></li>
					<li><%= link_to "Join", new_user_registration_path %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

dbpn/app/views/home/contact.html.erb
<h3>Get in touch with Petnamesdb</h3>
	<ul>
		<li>email: crew@petnamesdb.com </li>
	</ul>

dbpn/app/views/home/index.html.erb
<div class="jumbotron">
	<h1>Petnames database: A Curated Collection</h1>
	<p>We're fascinated by what people name the animals in their lives!</p>
</div>
<p>We have collected pet names from literature, film, indviduals, and institutions such as zoos and wildlife preserves. Each animal's record can include: name, common name or breed, dates of life, and a few notes about that particular animal.</p>

<p>If a name already appears in our list, a new individual who shares
	the same name can also be added. Yep, we can keep track of how many
	animals have been named "Underfoot"! Want to know how many different types of animals have been given the name "Spot"? We keep track of that too.</p>

dbpn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dbpn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'home/header' %>

<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>

		<% end %>
<%= yield %>
</div>

</body>
</html>

dbpn/app/views/listnames/_form.html.erb
<%= form_for(@listname) do |f| %>
<% if @listname.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@listname.errors.count, "error") %> prohibited this name from being added: </h2>

	<ul>
		<% @listname.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

dbpn/app/views/listnames/index.html.erb
<!--This page should list all of the names that are in the database.  
		EX: Aggie
				Annie
				Archie
				Bailey
		Each name should appear only once even if multiple indvidual animals share that name. Each name should be linked to a page which lists all of the individual animals who share that name. 
		Add name links? -->
		<h1>Master List of Petnames</h1>
		<h3>All of the Petnames we've collected</h3>
		<p>Click on a name to see the indvidual animals with that name.</p>
		<p><%= link_to 'Add a name', new_listname_path %></p>
			<table>
			<tbody>
					<% @listnames.each do |listname| %>
					<tr>
						<td><%= link_to listname.lname, listname_path(listname.lname) %></td>
						<!-- add link to list of animals with listname -->	
					</tr>
			</tbody>
		</table>

	</br>
<% end %>

dbpn/app/views/listnames/new.html.erb
<h1>Add A New Name</h1>

<%= render 'form' %>

<%= link_to 'Back', listnames_path %>

dbpn/app/views/listnames/show.html.erb
<!--This page could list all of the individual animals in the database.
	Each animal entry should display the breed of the individual.
	EX: Aggie, bearded collie
	Each animal entry should link to a new page (or an AJAX query) that
	displays that animals entire entry with name, breed, dates and notes.
	